repos:

  -  repo: https://github.com/pre-commit/mirrors-clang-format
     rev: v19.1.0
     hooks:
      - id: clang-format
        additional_dependencies: []  # Or specify version: [clang-format==17.0.6]
        args: ["--style=file"]  # Looks for .clang-format config file
        files: "\\.(cpp|hpp|cc|hh|c|h)$"


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: name-tests-test
      - id: requirements-txt-fixer

#  -   repo: https://github.com/cpplint/cpplint.git
#      rev: 2.0.0
#      hooks:
#        -   id: cpplint
